---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: jrei/systemd-${MOLECULE_OS:-ubuntu:20.04}
    privileged: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        netdata_installer: ${MOLECULE_NETDATA_INSTALLER:-kickstart}
verifier:
  name: ansible
