---
name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created, edited, published]
jobs:
  molecule_default:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        molecule-os:
          - ubuntu:18.04
          - ubuntu:20.04
          - debian:10
          - centos:8
          - fedora:latest
        netdata-installer:
          - kickstart
          - kickstart-static64

    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        env:
          MOLECULE_OS: ${{ matrix.molecule-os }}
          MOLECULE_NETDATA_INSTALLER: ${{ matrix.netdata-installer }}
  molecule_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_args: --scenario-name features
  publish:
    runs-on: ubuntu-latest
    needs:
      - molecule_default
      - molecule_features
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@v2
      - name: Upload to ansible-galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: '${{ secrets.GALAXY_API_KEY }}'
